spring:
  thymeleaf:
    prefix: classpath:/build/
  resources:
    static-locations:
    - classpath:/build/
server:
  port: 8080
  servlet:
    context-path: /backendninja
logging:
  level:
    org:
      springframework:
        web: DEBUG
  file: /Users/administrador/Source/backendninja/log.out